### ISSUE TITLE
Formulate chartist / fundamentalists strategies as python function

### ISSUE THREAD

**Issue by joerischasfoort** [LCfP/Agent-Based-Stock-Market-Model#12]
Formulate both a chartists and fundamentalist valuation function. Ideally the function has as input an asset and returns a valuation.

**Comment by ChristopherStockermans** [comment]
We wanted to implement chartist with the moving average trading rules. But can't find a way to make it work with a over the counter market. The chartists analyse the trend of the stock market and decide if they want to sell or buy for the market price, but don't calculate a specific value they give the stock. Therefore, deriving the trading price over the counter is difficult. In particular, when 2 chartists wants to trade.

**Comment by joerischasfoort** [comment]
They could use the prices from previous periods right? They do not need to update continuously during the over the counter market interaction. 

Why would two chartists trade then? Because they use different time horizons. One chartist might look at three periods back, while the other at two.

**Comment by ChristopherStockermans** [comment]
I have come up with the following(probably not written correctly but I hope you get the point.
def chartist():
  MALonglength = randint[50,200]
  MAShortlength = randint[15,50]
  MALong = sum(price.history[MALonglength])/MALonglength
  MAShort = sum(price.history[MAShortlength])/MAShortlength
  if MAShort<MALong:
    return(price.history[-1]*rand[0.6,0.8])
  elif MALong<MAShort:
    return(price.history[-1]*rand[1.1,1.3])
  
  When he buys, he will not buy something he won't  be able to sell later, even when the price is increasing. The increase he is willing to accept is random and dependent on the agent.
When he sells, he will sell for more than 0 because doing so is the same as holding a stock that fails. It can be thought that although the real life chartist perceives downslopes as future decrease, he is also aware that there could be a turning point. That is why he is only willing to loose a certain percentage, else he will hold and hope the stock will grow in the future or he gets a better offer. 
The interval is larger in buy due to risk aversion.

**Comment by ZireJP** [comment]
For now we will use a simple method of extrapolating the moving average of the stock.
Further implementation is combined in Issue #25
