### ISSUE TITLE
implement Coveralls and appveyor

### ISSUE THREAD

**Issue by joerischasfoort** [LCfP/Agent-Based-Stock-Market-Model#17]
Automate testing

**Comment by ZireJP** [comment]
Coveralls and CI works now on my fork. I used Travis instead of appveyor. We can add appveyor later if we want to specifically test on a windows env but I think that is unnecessary for now.

For this to work on the LCfP repo the organization needs to give access to coveralls and travis-ci. Not something I can do. Maybe @ApiumNL can initiate this?

**Comment by N-Wouda** [comment]
On this!

**Comment by N-Wouda** [comment]
I think I gave access, but we'll see soon enough with new PRs.
