### ISSUE TITLE
Tweak(ing) notebook for chartist behaviour (5)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Agent-Based-Stock-Market-Model#27]
Dependency on #25

**Comment by joerischasfoort** [comment]
Ok, I've worked on a new type of graph that shows both stock prices and volume. 

![volumesandprices](https://cloud.githubusercontent.com/assets/8150061/25947385/8a7f49de-364f-11e7-8f01-530361574d93.png)

The price chart is still a scatter plot as there are often no prices. Once this issue is fixed, I intend to replace it with a candlestick graph. 

Then it should look more like actual stock market graphs showcasing information about prices and volume: 

http://www.stockmarket-coach.com/images/reading-stock-charts-candlestick-chart.jpg

**Comment by N-Wouda** [comment]
Updated this to `5`, and assigned @joerischasfoort also.
