### ISSUE TITLE
General bug fixing (3)

### ISSUE THREAD

**Issue by N-Wouda** [LCfP/Agent-Based-Stock-Market-Model#37]

**Comment by N-Wouda** [comment]
Always on backlog since it's not really a well-defined 'issue'.

**Comment by joerischasfoort** [comment]
I found 3 bugs in the new pandas dataframe output which I have not been able to solve yet.

1 input certain columns in pandas as float instead of int
Transaction: id, Seed, period, amount of product columns should be integers instead of floats
2 The first Transactor id outputs the same for all three transactors (it should be different)
3 Objects table does not seem to work (multiple traders are the same object

**Comment by N-Wouda** [comment]
Regarding the first one, this is generally done by using [`astype`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.astype.html) (link to docs), where you pass a dict of 'column' => 'type' arguments.

Use `numpy.dtypes` for this, not Python defaults.

**Comment by joerischasfoort** [comment]
These bugs should now be fixed.
